### ISSUE TITLE
Question about the code

### ISSUE THREAD

**Issue by yasuobinggan** [mathilde-b/SFDA#1]
Hi,
what an interesting work! I have read the conference and journal version of the paper. I am new to this, I encountered some problems when running the code, there may be some missing modules in the project:
![420d32151e6d1fc8](https://user-images.githubusercontent.com/30293157/130348858-8ce50996-daa9-47d8-bdca-a3647f14db0b.jpg)
It seems that the MySampler.py file is missing.
![7d369077c2926fd0](https://user-images.githubusercontent.com/30293157/130349177-e4336130-133d-42d9-ba3b-9d0373582a3d.jpg)
![635990dd5973ed26](https://user-images.githubusercontent.com/30293157/130349220-b4035bb5-64dc-4394-b24d-d593841da1de.jpg)
There are also some missing modules in the utils.py file and main_sfda.py file, I can't list them all.
Can you fix them?
Best wishes!

**Comment by mathilde-b** [comment]
Hello yasuobinggan I'll fix this now thanks for bringing this up !

**Comment by mathilde-b** [comment]
Hello yasuobinggan, it's done now. Let me know how it goes, thanks !

**Comment by yasuobinggan** [comment]
Sorry for the late reply. I have run the code. There may be a variable name error in main_sfda.py. I guess that changing the variable name on line 111 to "all_dices_s" should solve the problem.
![66b1efd4e3d223cb](https://user-images.githubusercontent.com/30293157/131243839-252efe7c-5806-4993-ac09-2918e7bb499f.jpg)

And sorry to bother you again, there may be some problems with my running results:
![-618f8fcbee9947eb](https://user-images.githubusercontent.com/30293157/131243854-b2bbe811-160d-4a87-bd45-9baef20a61ea.jpg)

I suspect that there is something wrong with my data preprocessing method. I did the experiment on the prostate dataset. My data slicing code is as follows. Is this correct? If you can reply, thank you very much!
![-7b2650376cd60039](https://user-images.githubusercontent.com/30293157/131243859-e84b11dc-eb17-4af0-9617-79a2f40a6756.jpg)

Finally, thanks again for your open-source work!

**Comment by mathilde-b** [comment]
Hello, 
so yes I removed all the references to source metrics actually, thanks for noticing it, its useless in this project. I added the script create_slices.py which goes from 3D slices to 2D slices. It's the only pre-processing.
Regarding the results, did you use the network pretrained on the source domain which is contained in results/prostate/cesource/last.pkl ? The baseline for this model should have a dice of around 66% on the target dataset. Did you correctly use the site SA as the target dataset ? maybe I could make my dataset with my datasplit available also.

**Comment by yasuobinggan** [comment]
Hello,
I did use Site A as the target dataset, but I divided the first 20 data into the training dataset and the last 10 data into the validation dataset. In fact, I am not quite sure where the problem is, and I look forward to your dataset with your datasplit. I will experiment further to determine where I am wrong.
Thank you very much!

**Comment by mathilde-b** [comment]
Yes i'm checking as well to see where the problem would be ! but yes, I think I'm going to put the data set here, its simpler, I'm just checking privacy concerns. I'll let you know when its done !

**Comment by yasuobinggan** [comment]
Thanks again！: )

**Comment by mathilde-b** [comment]
Hello yasuobinggan,

I had forgotten that the original prostate data had 3 classes, 0,1 and 2. 1 and 2 correspond to 2 different parts of the prostate. In the project we just merge class 1 and class 2 together. I investigated and this is the reason of the problem above !

I added a script to do this:
python remap_values.py "/path/to/target/GT" "{2:1,1:1,0:0}"
This should do the trick, with this you should obtain the correct baseline and results !
Here is also my data split just in case : 
train:
Case00.nii.gz  Case04.nii.gz  Case10.nii.gz  Case13.nii.gz  Case16.nii.gz  Case21.nii.gz  Case25.nii.gz  Case29.nii.gz
Case01.nii.gz  Case06.nii.gz  Case11.nii.gz  Case14.nii.gz  Case18.nii.gz  Case23.nii.gz  Case27.nii.gz
Case03.nii.gz  Case09.nii.gz  Case12.nii.gz  Case15.nii.gz  Case19.nii.gz  Case24.nii.gz  Case28.nii.gz
val :
Case02.nii.gz  Case05.nii.gz  Case07.nii.gz  Case08.nii.gz  Case17.nii.gz  Case20.nii.gz  Case22.nii.gz  Case26.nii.gz

Let me know how it goes!

**Comment by yasuobinggan** [comment]
OK, I will try as soon as possible.

**Comment by yasuobinggan** [comment]
Thank you very much, I adjusted the data format according to your guidance and got the same result as the paper!
![-567663bd532c4eac](https://user-images.githubusercontent.com/30293157/131366810-abc8e980-ebd7-40e2-b916-f671b35eb369.jpg)

And the necessary save path may be missing in remap_values.py.
Finally, thanks for your work and patience!

**Comment by mathilde-b** [comment]
Great news ! thanks !

**Comment by alexbgl** [comment]
Hi @mathilde-b ,
thank you for sharing the code for your great work!
Where do I find the above-mentioned scripts `remap_values.py` and `create_slices.py`? DId I overlook them or did you remove them?
Thanks!

**Comment by mathilde-b** [comment]
Hello @alexbgl , I have justed added these scripts, let me know !

**Comment by alexbgl** [comment]
Thank you!
