### ISSUE TITLE
Dataset access request

### ISSUE THREAD

**Issue by MAhsanAkhtar** [mathilde-b/SFDA#3]
Can you please provide us preprocessed dataset  Heart Dataset used in the paper? Actually, we email guoyan.zheng@istb.unibe.ch but got an address not found against it. 
Furthermore, for the third dataset, is in NII format but doesn't contain Ground Truth in it. Kindly guide how can we use it with the code thanks.

**Comment by mathilde-b** [comment]
Hello
The heart dataset is here : 
https://drive.google.com/file/d/1m9NSHirHx30S8jvN0kB-vkd7LL0oWCq3/view
https://drive.google.com/file/d/1SJM3RluT0wbR9ud_kZtZvCY0dR9tGq5V/view
See here for details on the dataset:
https://github.com/carrenD/Medical-Cross-Modality-Domain-Adaptation

**Comment by mathilde-b** [comment]
The prostate dataset is here : 
https://drive.google.com/file/d/1TtrjnlnJ1yqr5m4LUGMelKTQXtvZaru-/view
See details here : 
https://liuquande.github.io/SAML/
The ground truth is indeed included.
Best,
Mathilde
