### ISSUE TITLE
Data preprocess of Heart Dataset

### ISSUE THREAD

**Issue by jeff51207** [mathilde-b/SFDA#4]
Hello, first thanks to your awesome work!

I'm going to use the heart dataset from [https://github.com/carrenD/Medical-Cross-Modality-Domain-Adaptation.](https://github.com/mathilde-b/CDA/issues/url) for test.

And I'm wondering how you preprocess the data in tfrecords format?

For label, I just trans it into gray-scale with values from 0~4.

And I'm not sure how to preprocess the image, because the images had already did some augumentation like crop, normalized...

Could you share your preprocess method or the data?

On the other side, there are some module missed in the project, like MySampler, can you fix them?

 Thanks!

**Comment by mathilde-b** [comment]
Hello Jeff
If you look at the link here, https://github.com/carrenD/Medical-Cross-Modality-Domain-Adaptation, the preprocessed data can be loaded in tfrecords format for the training/val, and nii format for the test. 

"The pre-processed and augmented training data repository can be downloaded [here](https://drive.google.com/file/d/1m9NSHirHx30S8jvN0kB-vkd7LL0oWCq3/view?usp=sharing), in the form of tfrecord for direct load. The testing CT data can be downloaded [here](https://drive.google.com/file/d/1SJM3RluT0wbR9ud_kZtZvCY0dR9tGq5V/view?usp=sharing), in the form of .nii with heart region cropped."

I didn't use any more preprocessing, just a normalisation:  Images are normalized to zero mean and unit variance.
For label, yes, 0-4 values I think (there are five classes counting background).

To read tfrecords in pytorch, you can use something like this : https://github.com/vahidk/tfrecord
Here is a tutorial https://medium.com/analytics-vidhya/how-to-read-tfrecords-files-in-pytorch-72763786743f

MySampler is not used, shouldn't be here, I'm removing the dependency, thanks !
Cheers !

**Comment by jeff51207** [comment]
Hi, 

Thanks for your reply, I will test it with your advice :)

**Comment by jeff51207** [comment]
Hi, sorry to bother you again.

I have read images and labels from tfrecords file, and save them as png file.

For image, I just read it and save it with astype(np.uint8).

For label, I read it and trans it from 256x256x3 to 256x256x1 grayscale image, and use 0~4 as it label value.

But when I start training, I meet the following error:

![image](https://user-images.githubusercontent.com/29098768/163798052-9568f83b-b98b-4085-97e2-6c4b87f6c6f2.png)

It seems the like there are some problems about the format of image? I still can't solve it after google for relative information.

Have you meet the problems before? 

Thanks!

**Comment by mathilde-b** [comment]
Hello ! It seems that you are training with the EntKLProp loss. Have you first successfully trained on the source domain with L_OR (CrossEntropy) successfully ? if you use whs.make, results will be saved in results/whs/cesource. Let me know if this also generates errors !

**Comment by jeff51207** [comment]
Hello, thank for your reply first!

I think I'am training with CrossEntropy loss, the error occurs in this line:

![image](https://user-images.githubusercontent.com/29098768/163812680-02035490-b281-4f0e-b208-c83d503badb2.png)

**Comment by mathilde-b** [comment]
Ok So there might be a shape or class nb problem. You should have 5 classes in you GT images. 
Could you try training by removing the -0 in python ? just comment the CFLAGS = -O line in whs.make (line 7). This will execute the assertions. 
See what error you get .
Then, something you can try is just removing the class weighting in the cross entropy loss, because in any case they are set to one. So comment this line, and replace mask_weighted by mask in the next one. 
#mask_weighted = torch.einsum("bcwh,c->bcwh", [mask, Tensor(self.weights).to(mask.device)])
loss = - torch.einsum("bcwh,bcwh->", [mask, log_p])

let me know what happens !

**Comment by jeff51207** [comment]
I still got the same error after comment the CFLAGS = -O.

And after replace mask_weighted with mask, I got the following error:
![image](https://user-images.githubusercontent.com/29098768/164008391-eec626ee-b3dd-4f42-aac4-a0f886e20520.png)

I try to google to debug it, and I think the problem may cause of an inconsistency between number of labels and number of output units, and I still test it now.

**Comment by mathilde-b** [comment]
Do you have CUDA available ? what is the results of torch.cuda.is_available() ? 
Your error is after the line 
pred_logits: Tensor = net(target_image)
(line 161 in main_sfda.py)
so at least this seems to work.
You should maybe print the shapes of pred_probs and label and check that they are the same
Let me know !

**Comment by jeff51207** [comment]
Hi, I have just check it with your advice, the CUDA is available, and the shape of probs and labels are different:

![image](https://user-images.githubusercontent.com/29098768/164046568-d2cccd4d-d328-4378-8d01-5c2e725c3708.png)

So should I reshape label from 256 x 256 x 1 grayscale image to 256 x 256 x 5, and use 0 or 1 to represent the label?

Thanks!

**Comment by mathilde-b** [comment]
Hello, ok so it is your labels which are wrong. The shape should be 256 x 256 x 5 yes, as I use one-hot encoding. So yes, [0,1,0,0,0] represents class 1, [0,0,1,0,0] represents class 2,...
This should be done automatically in the dataloader.py script. See nii_gt_transform line 73, which transforms to one-hot encoding. The choice of the preprocess is in whs.make, line 14: 
TT_DATA = [('IMG', nii_transform, False), ('GT', nii_gt_transform, False), ('GT', nii_gt_transform, False)]

**Comment by jeff51207** [comment]
Hi, thanks for your advice!

I have edit the code for one-hot encoding, and start training now!
 
I meet another error and debug now, but at least I successfully start training!

![image](https://user-images.githubusercontent.com/29098768/164231167-964301c7-2551-4efe-b99d-eaebc68ba611.png)

**Comment by mathilde-b** [comment]
Hello Jeff, I don't know why you get this error ! You can safely comment this in any case, it's just for logging
    #if not epc%10:
        #df_t = pd.DataFrame({
           #"val_ids":all_pnames,
          # "proposal_size":all_sizes2.cpu()})
        #df_t.to_csv(Path(savedir,mode+str(epc)+"sizes.csv"), float_format="%.4f", index_label="epoch")

Have you run into other errors ? Thanks !

**Comment by jeff51207** [comment]
Hello, after I comment the code for logging, I got the error that float NaN can't be convert to int after validation:

![image](https://user-images.githubusercontent.com/29098768/164769501-a7151997-7d2f-4f82-90ed-817e4f81de5a.png)

**Comment by mathilde-b** [comment]
hello
Just to be clear, are you still in the fully supervised source training phase? Are you using the cross-entropy loss for training it ?
This vector of losses + sizes are also for logging.. Do you know which of loss_se, loss_cons, loss_tot, size_mean, size_mean_pos, Size_gt_mean, gt_size_mean_pos is NaN ? 
I guess it may be size_mean_pos, if you are at the start of the training; 
You can just remove it and use 
losses_vec = [loss_se.mean().item(),loss_cons.mean().item(),loss_tot.mean().item()]
 
then you can comment in the dataset (line 357)

       df_t_tmp = pd.DataFrame({
            "epoch":i,
            "tra_loss_s":[tra_losses_vec[0]],
            "tra_loss_cons":[tra_losses_vec[1]],
            "tra_loss_tot":[tra_losses_vec[2]],
            "tra_size_mean":[tra_losses_vec[3]],
            "tra_size_mean_pos":[tra_losses_vec[4]],
            "val_loss_s":[val_losses_vec[0]],
            "val_loss_cons":[val_losses_vec[1]],
            "val_loss_tot":[val_losses_vec[2]],
            #"val_size_mean":[val_losses_vec[3]],
           #"val_size_mean_pos":[val_losses_vec[4]],
            #"val_gt_size_mean":[val_losses_vec[5]],
            #"val_gt_size_mean_pos":[val_losses_vec[6]],
            'tra_dice': [tra_target_vec[4]],
            'val_dice': [val_target_vec[4]],
            "val_dice_3d_sd": [val_target_vec[1]],
            "val_dice_3d": [val_target_vec[0]]})
Let me know if this works !

**Comment by jeff51207** [comment]
Hi, after validation, I got the following error when do HD:

![image](https://user-images.githubusercontent.com/29098768/164828715-7076c033-0c05-4582-9bc3-7855ef63839a.png)

**Comment by mathilde-b** [comment]
Hello Jeff, so the script dice3d.py reconstructs the 3D volume to calculate the 3D metrics. For this, you need to use the name structure of the slices. In the case that you are using the heart dataset, the name is structured the following way: "slice"+patient_nb+"__"+slice_nb+".nii".
You can transform the bool_p line in dice3d.py in the following.
bool_p = [int(re.split('_',re.split('slice',x.item())[1])[0])==p for x in all_pnames]
Let me know ! 
Cheers

**Comment by jeff51207** [comment]
Hi, sorry for lately reply, there are something wrong with my server, and it takes me some time to fix it.

Follow your advice, I start training and pass the first validation, but I will got this error at epoch 2 when validation:

![image](https://user-images.githubusercontent.com/29098768/165046793-17c66ada-e87e-4650-bc7a-de9c49793b39.png)

And I'm wondering whether you have the performance data of SFDA on heart dataset?
I tried CDA for heart dataset first, and the code of CDA seems to have some problem, so I moved to try SFDA.
But I only found the performance on heart dataset in CDA paper.
Did the architecture of code for heart dataset change to SFDA? Or it still use the architecture of CDA? 

Thank for your patience!

**Comment by mathilde-b** [comment]
Hello Jeff, maybe the easier thing would be to put do_hd=0 and do_asd=0. This way, you will not enter line 38. This turns off the calculation of the Hausdorff metric and the ASD metric. These are auxiliary metrics, it is not important to calculate them at each epoch of the fully supervised source training phase !
Then, I'm not sure I understand your question. SFDA and CDA are two different projects. SFDA uses less data at the adaptation phase. For both projects, the heart dataset was used as validation.
Let me know
 Cheers !

**Comment by jeff51207** [comment]
Ok, I start training without do_hd and do_asd, and it seems to be good so far. 
For second question, sorry, I think I got mixed up of CDA and SFDA haha.
And do you have the experiment result of SFDA on heart dataset? I couldn't find it in the paper of SFDA.

**Comment by mathilde-b** [comment]
ok good ! Once the source training is done, you can start with the adaptation phase; this is where the work begins ! :)
You should check the readme here, you have the info that you asked :) https://github.com/mathilde-b/SFDA
here is the link for our original MICCAI paper : https://link.springer.com/chapter/10.1007/978-3-030-59710-8_48
and here is the link for our ongoing journal extension: https://arxiv.org/abs/2005.03697
Cheers
Mathilde

**Comment by jeff51207** [comment]
Hi, I have finished the source training, and got some error when start domain adaptation:

![image](https://user-images.githubusercontent.com/29098768/165462666-9047ee33-a49f-4b41-a758-3fecb9e582fc.png)

First, after load the 8400 images in ct train folder, the state became to "on test", is it means that you will test first before start domain adaptation?
I think I'm a little bit confused about the training flow.

After it start test, it load 0 image and end training immediately, I think the reason is that I didn't create the data path for test data.
And I didn't see the path you store the test data in your dataset instance.

Thank you!

**Comment by mathilde-b** [comment]
Hello Jeff
The "on val " or "on test" print just says whether you are using the validation set or the test set for inference. did you split your data into a train, val, and test set ? change the names of the folders into "train", "val" and "test". The default path for inference will be "val". If you use the --ontest argument, then it will be "test".
The test dataset can be downloaded here 
https://drive.google.com/file/d/1SJM3RluT0wbR9ud_kZtZvCY0dR9tGq5V/view
Cheers

**Comment by jeff51207** [comment]
Hi, I have download the test data and put it in data/ct/, and renamed it as "test" folder.

But I still can't start training.

I found epoch been set as 0 in this following lines:

![image](https://user-images.githubusercontent.com/29098768/165526139-fced2acb-dc8d-4a7a-8e23-93ef73cbd1eb.png)

And I'm not sure why there are still some code about size predictor, I think it was used in CDA, not SFDA?

**Comment by mathilde-b** [comment]
Hello, yes you do need a size predictor here as well ! This is common to CDA and SFDA. Have you read the readme and downloaded the "sizes" folder which I put https://github.com/mathilde-b/SFDA/tree/main/sizes
Here you will find the coarse size predictors for each dataset.

**Comment by jeff51207** [comment]
Ok, I think I have already download the sizes in the beginning, so I have to edit other settings for sfda training?

this is the setting of my whs.make:

![image](https://user-images.githubusercontent.com/29098768/165529942-81d6fddc-82cf-4016-bc46-cd7b3074ed35.png)

**Comment by mathilde-b** [comment]
![image](https://user-images.githubusercontent.com/25257819/165534384-17c282f3-d81d-4952-8164-8bd9b29bb2ff.png)
 do you have the "sizes" file in your project directory ? with the whs.csv inside ? if you do, it should work

**Comment by jeff51207** [comment]
Yes, I do have whs.csv in sizes folder:

![image](https://user-images.githubusercontent.com/29098768/165536244-41d34791-99a6-451c-95c4-fc22e6876ea6.png)

But I still got False for size predictor:

![image](https://user-images.githubusercontent.com/29098768/165536374-b5349759-35c5-45a2-9b4d-b0a747c3c2bd.png)

**Comment by jeff51207** [comment]
Or maybe I should use other csv file?
Because I use png image file for training, not nii.

**Comment by mathilde-b** [comment]
Hello Jeff, if you are using .png instead of .nii, you can just change this in the whs.csv file !
Just open whs.csv with text editor, than replace ".nii" by ".png" everywhere.

Then, second thing : 
in whs.make, change "meansourcewtags" to "dumbpredwtags", as it is the current name of the size predictor column in the csv file.
Sorry about that !

**Comment by mathilde-b** [comment]
![image](https://user-images.githubusercontent.com/25257819/165564231-d7a09041-06ae-487a-a455-d31145be90df.png)

**Comment by jeff51207** [comment]
Ok, and I found a problem, because I directly parse image from tfrecord file, so the format name of images is "ctslice_{num}", which are different from your format.

![image](https://user-images.githubusercontent.com/29098768/165565408-d7147fab-e312-412e-a256-6ca8a1cd4d84.png)

**Comment by mathilde-b** [comment]
OK ! so this is not important for the TRAINING target data : in your case, you can just rename all your slices adding '"__1"'at the end and you will be fine. Also you should remove the underscore between "ctslice" and "{num}", to have "ctslice{num}". 
do this :
`cd data/train/IMG`
`for i in *.png; do mv "$i" "${i%.*}_1.png"; done`
`cd ..`
`cd GT`
`for i in *.png; do mv "$i" "${i%.*}_1.png"; done`


BUT for the test data, it is important to keep the names because they identify the patient : 
ctslice{PATIENT_NB}_{slice_nb}
This is important because for testing, we want to calculate in 3D the metrics, for each patient independently.
so be careful to keep this format of names !
Cheers

**Comment by jeff51207** [comment]
Ok, and after I change the format of the name, I will got these two error when loading data:
one is "SliceDataset' object has no attribute 'bounds_generator'"
another seems to be a problem of size different between tensor

![image](https://user-images.githubusercontent.com/29098768/165724918-f98039ff-1e5f-4d1a-bdd8-f792bdfbc5fe.png)

![image](https://user-images.githubusercontent.com/29098768/165725076-d4fe3d00-2df9-410d-acb2-4be265ae3583.png)

**Comment by mathilde-b** [comment]
Both errors stem from the same problem, which is that "ctslice5829_1.png" couldn't be found in the whs.csv dataset.

**Comment by jeff51207** [comment]
Thanks!

So I have to edit the code for removing the image that couldn't be found in whs.csv from training?

**Comment by mathilde-b** [comment]
No actually the thing is, it shouldn't be the case that a slice is not found on whs.csv, all should be there ! ctslice5829_1.nii is in my original whs.csv file, so if you transformed properly ctslice5829_1.nii in ctslice5829_1.png in the whs file, then it should be found

**Comment by jeff51207** [comment]
Ok, I will check it again, thank for your help!

**Comment by jeff51207** [comment]
May I ask the meaning of this section of code?

![image](https://user-images.githubusercontent.com/29098768/165775389-5cdc2f9e-f644-4f94-9276-b387158b0a52.png)

I try to print logs in this section, and I found most of the image would not enter this section, and this time I got error in this section when load ctslice8242_1.png when executing "gt_prop = torch.ones_like(est_prop)*bounds/(w*h)"
But I have check that this image is in my data folder.

![image](https://user-images.githubusercontent.com/29098768/165775593-0b66e17d-ad65-4f6c-ad66-8f876b0103b3.png)

Thanks!

**Comment by mathilde-b** [comment]
this section is the calculation of the gt_size_estimation and the predicted_size_estimation
There are two options of estimation for the gt_size_estimation : or use the ground truth (curi = False), or use "curriculum learning" (curi =True), meaning using an estimation of the gt_size which is stored in whs.csv

Maybe have a problem with the separator in the csv file ? 
Everytime you have a "not eval" print, it means that the slice in question was not found in whs.csv . This will produce an error

**Comment by jeff51207** [comment]
I check it again and make sure the file name are the same, so I think the problem is not about whether the image exist.

There are almost at least one "not eval" for every image:
![image](https://user-images.githubusercontent.com/29098768/165792628-06f40041-2299-456b-945d-bfcbd42d6b45.png)


sometimes the image have two "not eval" but error doesn't occur:
![image](https://user-images.githubusercontent.com/29098768/165792490-2d71f7d4-8f4f-430c-82f5-67096b4cfc0e.png)

**Comment by mathilde-b** [comment]
change 'curi':True to 'curi':False (ie use the ground truth to estimate size) in the whs.make and let's see if this works

**Comment by jeff51207** [comment]
Hi, sorry for lately reply, I was on vacation these days.

After I change curi from true to False, I got the following error:

![image](https://user-images.githubusercontent.com/29098768/166482064-74975ddc-d082-4703-b065-c4407bc09a54.png)

I think you missed the assignment of loss_2.

Thanks!

**Comment by mathilde-b** [comment]
Hey sorry these are also logging things which are  not necessary for you, you can just comment this line 181

**Comment by jeff51207** [comment]
Ok, after I comment it, it start training for about 5 minutes, but the following error occurs again:

![image](https://user-images.githubusercontent.com/29098768/166669652-35294707-0bdb-47e8-ad30-5077e50baed5.png)

![image](https://user-images.githubusercontent.com/29098768/166669682-7bec20b2-10c2-45eb-a0d5-a90f27b76066.png)

**Comment by mathilde-b** [comment]
Hey Jeff, you still have the same problem , ctslice4677_1.png is not in the csv file it seems. You can do this : change PredictionBounds in whs.make by PreciseBounds.

Let's see if this works !

**Comment by jeff51207** [comment]
OK, after change PredictionBounds to PreciseBounds, I successfully finished the training!

But I think there are still some problem when training, it seems to skip the validation stage, and the dice value is lower than expect:
![image](https://user-images.githubusercontent.com/29098768/166870843-0514ffca-2ebd-4edc-93de-09aff00560b9.png)

And is there any function that can test the model by png image input, and visualize the predict result?

Thanks!

**Comment by jeff51207** [comment]
Hi, sorry for another problem, I know that I have asked a lot of question, it may be annoying, so just feel free to reply it :)

I try to edit the code by myself after last reply, I increase the number of epoch from 100 to 500, and also make the valid data start to work, and the performance seems good now, it's achieve 7x - 80 in DICE value:

![image](https://user-images.githubusercontent.com/29098768/168863164-28cde2d1-7afc-41ab-9768-654164551522.png)

But now I meet a problem, I just check that the DICE value when validation is about 7x, but after validation, the average DICE value seems to be wrong, I print it and found it equals 0.0, which didn't match the value in the previous picture:

![image](https://user-images.githubusercontent.com/29098768/168865861-d84ee1bb-2724-4ff3-a9b3-03612a6ad9db.png)

It make the step of checking best epoch fail, so I wondering whether any problem exist when calculate the average DICE of valid data?

Thanks!

**Comment by wangjiakun13** [comment]
> Hi, sorry to bother you again.
> 
> I have read images and labels from tfrecords file, and save them as png file.
> 
> For image, I just read it and save it with astype(np.uint8).
> 
> For label, I read it and trans it from 256x256x3 to 256x256x1 grayscale image, and use 0~4 as it label value.
> 
> But when I start training, I meet the following error:
> 
> ![image](https://user-images.githubusercontent.com/29098768/163798052-9568f83b-b98b-4085-97e2-6c4b87f6c6f2.png)
> 
> It seems the like there are some problems about the format of image? I still can't solve it after google for relative information.
> 
> Have you meet the problems before?
> 
> Thanks!



> Hi, sorry to bother you again.
> 
> I have read images and labels from tfrecords file, and save them as png file.
> 
> For image, I just read it and save it with astype(np.uint8).
> 
> For label, I read it and trans it from 256x256x3 to 256x256x1 grayscale image, and use 0~4 as it label value.
> 
> But when I start training, I meet the following error:
> 
> ![image](https://user-images.githubusercontent.com/29098768/163798052-9568f83b-b98b-4085-97e2-6c4b87f6c6f2.png)
> 
> It seems the like there are some problems about the format of image? I still can't solve it after google for relative information.
> 
> Have you meet the problems before?
> 
> Thanks!

抱歉打扰一下，我想问一下您是怎么处理MMWHS这个数据集的tfrecords文件的并把它们保存为png的，能参考一下您的代码吗

**Comment by zqp1226358** [comment]
Sorry to bother you, I would like to ask how you process the tfrecords files of the MMWHS dataset and save them as png, I have encountered a little difficulty, can I refer to your code? @jeff51207
