### ISSUE TITLE
name 'Sampler' is not defined

### ISSUE THREAD

**Issue by FJGEODEV** [mathilde-b/SFDA#6]
Hi, it's very interesting and good work, thanks for sharing the codes. I have a question, it looks like it's still missing the "Sampler" file as shown below. I saw you have a closed issue that discussed this `"MySampler.py`, could you help to add it?

`Traceback (most recent call last):
  File "main_sfda.py", line 21, in <module>
    from dataloader import get_loaders
  File "/home/fj/Research/domainadaption/SFDA/dataloader.py", line 280, in <module>
    class PatientSampler(Sampler):
NameError: name 'Sampler' is not defined
`

Thanks.

**Comment by mathilde-b** [comment]
Hey, sorry for the late reply, I just added the sampler class in dataloader.py ! should work now
Cheers
