### ISSUE TITLE
Poor performance on cardiac dataset

### ISSUE THREAD

**Issue by shizoda** [mathilde-b/SFDA#8]
Hello Mathilde,

I'm very interested in your work.
Since the code did not work as out-of-the-box, I changed several points and uploaded [here](https://github.com/shizoda/SFDA). Briefly,
- Restored the `Sampler` class on `dataloader.py` from
  - https://github.com/SRDAMICCAI/Source-Relaxed-Domain-Adaptation/blob/master/MySampler.py
  - Should I keep it removed?
- Options in the makefiles
  - Added `lamb_conspred` as 1 (Is it appropriate? I have not understood what it is)
  - Disabled `--dice-3d` due to some run-time error
  - Made some parameters follow your experimental settings on the Medical Image Analysis paper, e.g. batch size as 150
- Converting images, ground-truths and results to NII files for visualization on viewers, such as MITK Workbench

Now I can run `cesource`, `sfda` and `cesourceim` to get results.

It worked very well for the prostate dataset. However, performance for the cardiac (WHS) dataset is still poor.
Following the uploaded `whs.make`, training is performed on CT and validation on MR (if I understand correctly). 

If you have experienced similar situations, I'd love to hear some suggestions.

Many thanks!
shizoda

**Prostate dataset**
![SFDAresultProstate](https://user-images.githubusercontent.com/34496702/228174127-82fa2e50-bdaf-4f16-b24c-564376e6730e.png)

**Cardiac (WHS) dataset**
![SFDAresult](https://user-images.githubusercontent.com/34496702/228174146-97651efa-5dbb-435a-ae87-0f9c5c59f6c6.png)

**Comment by zqp1226358** [comment]
Sorry to bother you, I would like to ask how you process the tfrecords files of the MMWHS dataset and save them as png, I have encountered a little difficulty, can I refer to your code? @shizoda

**Comment by shizoda** [comment]
I found the problem.
In make.whs, `M_WEIGHTS_ul` is defined but `M_WEIGHTS_uce` is referred. Thank you!
